name: dwt_da
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - cudnn
  - numpy
  - matplotlib
  - opencv
  - pillow
  - scipy
  - jupyter
  - notebook
  - tensorflow
  - pip:
      - tqdm
      - pandas
      - sklearn
      - seaborn
      - tensorboardX
